### ISSUE TITLE
Updating dependencies without setting the filename causes late error

### ISSUE THREAD

**Issue by therc** [scele/rules_python#17]
Running `@pip_deps//:update` without setting `requirements_bzl` results, toward the end of the whole procedure, in

`mv: cannot move '/tmp/tmp.m6z5a8nZUU' to '': No such file or directory`

This is due to the command `mv "$REQUIREMENTS_BZL_TEMP" "$REQUIREMENTS_BZL"`. The latter variable will be empty. Perhaps an early check should catch this before doing the rest of the work.

**Comment by scele** [comment]
I'm removing the update.sh.tpl shell script in my big upcoming refactoring https://github.com/scele/rules_python/pull/12. In that branch, we do fail earlier, but with very unhelpful error message...
