### ISSUE TITLE
FR: drop wheel directories?

### ISSUE THREAD

**Issue by therc** [scele/rules_python#23]
Some wheels are heavy with files. Repeat that for every target that uses them and you have a lot of symlinks. A few random examples:

```
 548 ./pip__tensorflow_1_10_0/tensorflow/python
 599 ./pip__pytz_2018_9/pytz/zoneinfo
 683 ./pip__pylint_1_5_1/pylint/test
1157 ./pip__tensorflow_1_10_0/tensorflow/contrib
3280 ./pip__tensorflow_1_10_0/tensorflow/include
```

Would it make sense or be feasible to allow dropping e.g. `tensorflow/include`, either at build or extract time, if you never use the C++ headers?

**Comment by therc** [comment]
This is the isort code, for the record: https://github.com/timothycrosley/isort/blob/develop/isort/finders.py#L151

**Comment by scele** [comment]
Should already be possible at extract time:

```
overrides = {
    "tensorflow": {
        "patch_cmds": [
            "rm -rf tensorflow/include",
        ],
    },
}
pip_import(
    ...
    requirements_overrides = overrides,
)
```
or build time (but this is a bit awkward):
```
overrides = {
    "tensorflow": {
        "additional_build_content": "@//third_party/tensorflow:BUILD.custom",
        "additional_targets": ["my_stripped_tensorflow"],
    },
}
pip_import(
    ...
    requirements_overrides = overrides,
)

# third_party/tensorflow:BUILD.custom:
py_library(
    name = "my_stripped_tensorflow",
    srcs = glob(..., exclude=["include/**"]),
    deps = ...
)

# when using:
requirement("tensorflow", target = "my_stripped_tensorflow")
```

**Comment by therc** [comment]
Makes sense, I'll give the patch command approach a shot. Thanks!
At some point, when you think the rules are stable enough in terms of interface and features, I can help write documentation.
